version: "3.8"
services:
  api:
    build: .
    container_name: flask
    restart: "always"
    environment:
      FLASK_APP: run.py
    volumes:
      - .:/usr/src/app
    expose:
      - 8080
    depends_on:
      - db
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    volumes:
    - /application/static/:/static
    depends_on:
      - api
    ports:
      - "80:80"
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ex_db
    ports:
      - 5900:5432
volumes:
  postgres_data: