"""fix link photo

Revision ID: 0a48163c6bf0
Revises: 947defd854c7
Create Date: 2021-07-10 17:34:42.431191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a48163c6bf0'
down_revision = '947defd854c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ad_photos_link_key', 'ad_photos', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('ad_photos_link_key', 'ad_photos', ['link'])
    # ### end Alembic commands ###
