"""empty message

Revision ID: 3710f1790611
Revises: 59aad84c1551
Create Date: 2021-09-07 13:45:42.869942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3710f1790611'
down_revision = '59aad84c1551'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ads', sa.Column('connection', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ads', 'connection')
    # ### end Alembic commands ###
